openapi: 3.0.0
info:
  title: Categories API
  version: 1.0.0
paths:
  /categories:
    get:
      summary: Retrieves all categories
      tags:
        - Categories
      responses:
        '200':
          description: A list of all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The category ID
                    name:
                      type: string
                      description: The name of the category
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
