openapi: 3.0.0
info:
  title: Categories API
  version: 1.0.0
paths:
  /categories/{category_id}:
    put:
      summary: Updates a category by ID
      tags:
        - Categories
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The updated name of the category
                  example: "Updated Desserts"
      responses:
        '200':
          description: The updated category
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The category ID
                  name:
                    type: string
                    description: The updated name of the category
        '400':
          description: Bad request, missing fields or invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
